/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyGrid {
    }
}
declare global {
    interface HTMLMyGridElement extends Components.MyGrid, HTMLStencilElement {
    }
    var HTMLMyGridElement: {
        prototype: HTMLMyGridElement;
        new (): HTMLMyGridElement;
    };
    interface HTMLElementTagNameMap {
        "my-grid": HTMLMyGridElement;
    }
}
declare namespace LocalJSX {
    interface MyGrid {
    }
    interface IntrinsicElements {
        "my-grid": MyGrid;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-grid": LocalJSX.MyGrid & JSXBase.HTMLAttributes<HTMLMyGridElement>;
        }
    }
}
